MealPlan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls'))
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>', views.details, name='details')
]

products/models.py
from django.db import models
from django.forms import CharField


class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    image_url = models.CharField(max_length=2048, default='')
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    calories = models.IntegerField(default=0)
    eda_id = models.IntegerField(default=0)

    def __str__(self):
        return self.name

MealPlan/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

products/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Product
import random
from .parser import parse


def index(request):
    meat = Product.objects.filter(type__name="Meat")
    sides = Product.objects.filter(type__name='Sides')
    random_meat = random.choice(meat)
    random_sides = random.choice(sides)
    return render(request, 'products/index.html', {'random_meat': random_meat, 'random_sides': random_sides})


def details(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    URL_TEMPLATE = f"https://eda.ru/recepty/ingredienty/{product.eda_id}"
    parse_list = parse(url=URL_TEMPLATE)
    recipe_name = [item['name'] for item in parse_list]
    recipe_preptime = [item['prep_time'] for item in parse_list]
    return render(request, 'products/details.html', {'product': product, 'parse_list': parse_list, 'recipe_name': recipe_name, 'recipe_preptime': recipe_preptime})

products/templates/products/details.html
{% extends 'base.html' %}

{% block content %}
    <dl>
        <dt>Product</dt>
        <dd>{{ product.name }}</dd>
        <dt>Type</dt>
        <dd>{{ product.type }}</dd>
        <dt>Calories in 100 g</dt>
        <dd>{{ product.calories }}</dd>
    </dl>

    {% for item in parse_list %}
        <div class="card" style="width: 18rem;">
            <img src={{ product.image_url }} class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title">{{ recipe_name }}</h5>
            <p class="card-text">Время приготовления: {{ recipe_preptime }}.</p>
            <a href="#" class="btn btn-primary">Посмотреть рецепт</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

products/templates/products/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <p>We suggest having 
            <a href="{% url 'products:details' random_meat.id %}">{{ random_meat|lower }}</a> 
            with <a href="{% url 'products:details' random_sides.id %}">{{ random_sides|lower }}</a>.
        </p>
    </div>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>MealPlan</title>
    <style>
        body {background-color: DarkSeaGreen;}
        .container {
            display: grid;
            align-items: center;
            height: 600px;
            text-align: center;
        }
        p {
            font-size: x-large;
            }
        a {
          text-decoration: none;
          color: DarkGreen;
        }
        button {
          max-width: 400px;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-light" style="background-color: DarkSeaGreen;">
        <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">
          <a href={% url 'products:index' %}>MealPlan</a>
        </span>
        </div>
        </nav>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<a href={% url 'products:index' %}>
    <button type="button" class="btn btn-success btn-lg">
        Click for some meal suggestions
    </button>
</a>
{% endblock  %}